databases:
  - name: fusion-lap
    databaseName: neondb
    user: LucasPires50

services:
  - type: web
    name: fusion-lap
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn fusion.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: neondb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4