# Generated by Django 5.0 on 2023-12-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cargo_alter_servico_icone_alter_servico_servico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipe',
            options={'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipes'},
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('init-cog', 'Engrenagem'), ('init-layers', 'Desing'), ('init-mobile', 'Mobile'), ('init-stats-up', 'Gráfico'), ('init-rocket', 'Foguete'), ('init-users', 'Usuários')], max_length=13, verbose_name='Icone'),
        ),
    ]
