# Generated by Django 5.0 on 2024-01-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('init-rocket', 'Foguete'), ('init-cog', 'Engrenagem'), ('init-layers', 'Desing'), ('init-users', 'Usuários'), ('init-mobile', 'Mobile'), ('init-stats-up', 'Gráfico')], max_length=13, verbose_name='Icone'),
        ),
    ]
