# Generated by Django 5.0 on 2024-01-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-layers', 'Desing'), ('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile'), ('lni-users', 'Usuários'), ('lni-stats-up', 'Gráfico')], max_length=13, verbose_name='Icone'),
        ),
    ]
