# Generated by Django 5.0 on 2024-01-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_recurso_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-laptop-phone', 'Celular'), ('lni-leaf', 'Folha'), ('lni-users', 'Usuários'), ('lni-layers', 'Camadas'), ('lni-stats-up', 'Gráfico'), ('lni-cog', 'Engrenagem'), ('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Design')], max_length=16, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-laptop-phone', 'Celular'), ('lni-leaf', 'Folha'), ('lni-users', 'Usuários'), ('lni-layers', 'Camadas'), ('lni-stats-up', 'Gráfico'), ('lni-cog', 'Engrenagem'), ('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Design')], max_length=16, verbose_name='Icone'),
        ),
    ]
