# Generated by Django 5.0 on 2024-01-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_equipe_bio_alter_recurso_icone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='descricao',
            field=models.TextField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Celular'), ('lni-leaf', 'Folha'), ('lni-layers', 'Camadas'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile')], max_length=16, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Celular'), ('lni-leaf', 'Folha'), ('lni-layers', 'Camadas'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile')], max_length=16, verbose_name='Icone'),
        ),
    ]
