# Generated by Django 5.0 on 2024-01-15 13:34

import core.models
import django.core.validators
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_plano_icone_alter_plano_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='icone',
            field=models.CharField(choices=[('lni-drop', 'Gota'), ('lni-star', 'Estrela'), ('lni-stats-up', 'Gráfico'), ('lni-leaf', 'Folha'), ('lni-mobile', 'Mobile'), ('lni-users', 'Usuários'), ('lni-cog', 'Engrenagem'), ('lni-package', 'Caixa'), ('lni-layers', 'Camadas'), ('lni-rocket', 'Foguete'), ('lni-layers', 'Design'), ('lni-laptop-phone', 'Celular')], max_length=16, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-drop', 'Gota'), ('lni-star', 'Estrela'), ('lni-stats-up', 'Gráfico'), ('lni-leaf', 'Folha'), ('lni-mobile', 'Mobile'), ('lni-users', 'Usuários'), ('lni-cog', 'Engrenagem'), ('lni-package', 'Caixa'), ('lni-layers', 'Camadas'), ('lni-rocket', 'Foguete'), ('lni-layers', 'Design'), ('lni-laptop-phone', 'Celular')], max_length=16, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-drop', 'Gota'), ('lni-star', 'Estrela'), ('lni-stats-up', 'Gráfico'), ('lni-leaf', 'Folha'), ('lni-mobile', 'Mobile'), ('lni-users', 'Usuários'), ('lni-cog', 'Engrenagem'), ('lni-package', 'Caixa'), ('lni-layers', 'Camadas'), ('lni-rocket', 'Foguete'), ('lni-layers', 'Design'), ('lni-laptop-phone', 'Celular')], max_length=16, verbose_name='Icone'),
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagens')),
                ('nome', models.CharField(max_length=50, verbose_name='Name')),
                ('depoimento', models.TextField(max_length=100, verbose_name='Descrição')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Nota')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
    ]
